name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies & Build
        run: |
          npm install --no-audit --no-fund --loglevel=error
          npm run build
        
      - name: Install Firebase Tools Globally
        run: npm install -g firebase-tools --no-audit --no-fund --loglevel=error
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CITY_CONTACTS_APP }}'
          projectId: city-contacts-app
          channelId: live
